-- FICUS module 1: Figs and tags.
-- Run once in the Supabase SQL Editor. Safe to re-run.
--
-- `sparks` mirrors the local SQLite table column-for-column. Figs are rows with
-- item_type = 'spark' and status = 'in_cloud'; later modules (tasks, trackers,
-- projects, references) store their rows in this same table.

create table if not exists public.sparks (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title             text not null,
  raw_content       text,
  source_url        text,
  topic_tag         text,
  source_type       text,
  status            text not null default 'in_cloud',
  promoted_to_type  text,
  promoted_to_id    bigint,
  graduated_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  item_type         text not null default 'spark',
  is_done           integer not null default 0,
  assignee          text default 'Me',
  extra_data        jsonb not null default '{}'::jsonb,
  due_date          text,
  due_time          text,
  project_id        bigint,
  phase_id          text,
  folder_id         bigint,
  is_pinned         integer not null default 0,
  habit_status      text default 'active',
  project_status    text default 'active',
  linked_vision_id  bigint,
  deadline          text,
  start_time        text,
  end_time          text,
  is_routine        integer not null default 0,
  recurrence_days   text,
  task_status       text default 'pending',
  drop_reason       text,
  drop_note         text,
  postponed_count   integer not null default 0,
  end_date          text,
  notes             text,
  is_parked         integer not null default 0,
  entry_type        text default 'task',
  is_theme_of_day   integer not null default 0,
  accent_color      text,
  emoji             text,
  is_all_day        integer not null default 0,
  is_multiday       integer not null default 0,
  pos_x             integer not null default 100,
  pos_y             integer not null default 100,
  color_theme       text default 'beige',
  group_name        text
);

create index if not exists sparks_user_type_status_idx
  on public.sparks (user_id, item_type, status, created_at desc);

create table if not exists public.tags (
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name        text not null check (name <> ''),
  color       text not null default 'slate',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  primary key (user_id, name)
);

-- Keep updated_at current on every edit.
create or replace function public.ficus_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sparks_touch_updated_at on public.sparks;
create trigger sparks_touch_updated_at
  before update on public.sparks
  for each row execute function public.ficus_touch_updated_at();

drop trigger if exists tags_touch_updated_at on public.tags;
create trigger tags_touch_updated_at
  before update on public.tags
  for each row execute function public.ficus_touch_updated_at();

-- Row Level Security: each signed-in user can only see and change their own rows.
alter table public.sparks enable row level security;
alter table public.tags enable row level security;

drop policy if exists "Users manage their own sparks" on public.sparks;
create policy "Users manage their own sparks"
  on public.sparks
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage their own tags" on public.tags;
create policy "Users manage their own tags"
  on public.tags
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.sparks to authenticated;
grant select, insert, update, delete on public.tags to authenticated;
revoke all on public.sparks from anon;
revoke all on public.tags from anon;
