-- FICUS module 3: Log and Time (tasks, events, log entries) plus checklist templates.
-- Run once in the Supabase SQL Editor after 02_trackers.sql. Safe to re-run.
--
-- Tasks, events and Daily Log entries need no new table: each one is a `sparks`
-- row with item_type = 'task' and entry_type = 'task' | 'event' | 'log'. Every
-- column they use (due_date, start_time, end_time, task_status, is_parked, ...)
-- was created by module 1, and module 1's row-level security policy already
-- limits every sparks row to its owner. This script adds the indexes those
-- pages query by, and the one new table: saved checklist templates.

-- Time page and calendar: a user's tasks by day.
create index if not exists sparks_user_tasks_by_day_idx
  on public.sparks (user_id, due_date, due_time)
  where item_type = 'task';

-- Daily Log: entries filed under a stream day.
create index if not exists sparks_user_stream_date_idx
  on public.sparks (user_id, (extra_data ->> 'stream_date'))
  where item_type = 'task';

-- Scheduling a task or event writes one "active" Log entry per day; this finds it.
create index if not exists sparks_user_active_schedule_logs_idx
  on public.sparks (user_id, id)
  where item_type = 'task' and (extra_data ->> 'is_active_schedule_log') = 'true';

-- Checklist templates: reusable item lists for task checklists.
create table if not exists public.checklist_templates (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name        text not null check (name <> ''),
  items       jsonb not null default '[]'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists checklist_templates_user_idx
  on public.checklist_templates (user_id);

drop trigger if exists checklist_templates_touch_updated_at on public.checklist_templates;
create trigger checklist_templates_touch_updated_at
  before update on public.checklist_templates
  for each row execute function public.ficus_touch_updated_at();

-- Row Level Security: each signed-in user can only see and change their own templates.
alter table public.checklist_templates enable row level security;

drop policy if exists "Users manage their own checklist templates" on public.checklist_templates;
create policy "Users manage their own checklist templates"
  on public.checklist_templates
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

grant select, insert, update, delete on public.checklist_templates to authenticated;
revoke all on public.checklist_templates from anon;
