-- FICUS module 5: the Project page (project binders).
-- Run once in the Supabase SQL Editor after 04_storage.sql. Safe to re-run.
--
-- A project is a binder: a cover (title, description, colours, tracker, ship
-- date), sections and sub-sections holding up to six columns of blocks, and
-- legacy checklist lines. These three tables mirror the local SQLite tables.
--
-- Tasks and events link to a project through its blocks: a Task or Event block
-- stores the id of a `sparks` task row, so the item lives in Time and the Daily
-- Log and the project shows it live. A project or section ship date creates a
-- commitment event (also a `sparks` row) whose id is kept in ship_event_id.

create table if not exists public.projects (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title          text not null check (title <> ''),
  description    text not null default '',
  cover_color    text,
  cover_image    text,
  spine_color    text,
  ship_date      text,
  ship_event_id  bigint references public.sparks (id) on delete set null,
  tracker        jsonb,
  status         text not null default 'active' check (status in ('active', 'graduated')),
  graduated_at   timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- extra_columns holds every column after the first; the first column's blocks
-- live in `blocks`, its width in main_width and its tray layout in main_layout.
create table if not exists public.project_sections (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null default auth.uid() references auth.users (id) on delete cascade,
  project_id     bigint not null references public.projects (id) on delete cascade,
  parent_id      bigint references public.project_sections (id) on delete cascade,
  section_index  integer not null,
  title          text not null check (title <> ''),
  blocks         jsonb not null default '[]'::jsonb,
  extra_columns  jsonb not null default '[]'::jsonb,
  main_width     integer,
  main_layout    jsonb not null default '{}'::jsonb,
  cover_color    text,
  cover_image    text,
  spine_color    text,
  ship_date      text,
  ship_event_id  bigint references public.sparks (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create table if not exists public.project_lines (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null default auth.uid() references auth.users (id) on delete cascade,
  section_id    bigint not null references public.project_sections (id) on delete cascade,
  content       text not null default '',
  is_completed  boolean not null default false,
  blocks        jsonb not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists projects_user_idx
  on public.projects (user_id, created_at desc);
create index if not exists project_sections_project_idx
  on public.project_sections (project_id, section_index);
create index if not exists project_sections_parent_idx
  on public.project_sections (parent_id);
create index if not exists project_lines_section_idx
  on public.project_lines (section_id, created_at);

drop trigger if exists projects_touch_updated_at on public.projects;
create trigger projects_touch_updated_at
  before update on public.projects
  for each row execute function public.ficus_touch_updated_at();

drop trigger if exists project_sections_touch_updated_at on public.project_sections;
create trigger project_sections_touch_updated_at
  before update on public.project_sections
  for each row execute function public.ficus_touch_updated_at();

drop trigger if exists project_lines_touch_updated_at on public.project_lines;
create trigger project_lines_touch_updated_at
  before update on public.project_lines
  for each row execute function public.ficus_touch_updated_at();

-- Row Level Security: each signed-in user can only see and change their own
-- rows, and can only attach sections and lines to a project they own.
alter table public.projects enable row level security;
alter table public.project_sections enable row level security;
alter table public.project_lines enable row level security;

drop policy if exists "Users manage their own projects" on public.projects;
create policy "Users manage their own projects"
  on public.projects
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage their own project sections" on public.project_sections;
create policy "Users manage their own project sections"
  on public.project_sections
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.projects p
      where p.id = project_id and p.user_id = (select auth.uid())
    )
    and (
      parent_id is null
      or exists (
        select 1 from public.project_sections s
        where s.id = parent_id and s.user_id = (select auth.uid())
      )
    )
  );

drop policy if exists "Users manage their own project lines" on public.project_lines;
create policy "Users manage their own project lines"
  on public.project_lines
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.project_sections s
      where s.id = section_id and s.user_id = (select auth.uid())
    )
  );

grant select, insert, update, delete on public.projects to authenticated;
grant select, insert, update, delete on public.project_sections to authenticated;
grant select, insert, update, delete on public.project_lines to authenticated;
revoke all on public.projects from anon;
revoke all on public.project_sections from anon;
revoke all on public.project_lines from anon;
