-- FICUS module 6: Vision, Vault and Legacy.
-- Run once in the Supabase SQL Editor after 05_projects.sql. Safe to re-run.
--
-- Vision: scrapbook vision boards with their goals, linked commitments
-- (projects, trackers, notebooks) and attached blocks, plus the sticker,
-- sticky-pad and palette libraries used by the board editor.
--
-- Vault: notebooks (chapters and lines) arranged in stacks on shelves, and the
-- folders that file Vault references. References themselves are `sparks` rows
-- with item_type = 'reference' (see 01_figs_and_tags.sql). Cover images and
-- chapter backgrounds are uploaded through the `uploads` bucket (04_storage.sql).
--
-- Legacy has no tables of its own: it reads fulfilled vision boards and
-- graduated trackers.

/* ---------- Vision ---------- */

create table if not exists public.vision_boards (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title           text not null check (title <> ''),
  canvas          jsonb not null default '{"objects": []}'::jsonb,
  thumbnail_data  text,
  status          text not null default 'active' check (status in ('active', 'fulfilled')),
  fulfilled_at    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create table if not exists public.vision_goals (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null default auth.uid() references auth.users (id) on delete cascade,
  vision_id     bigint not null references public.vision_boards (id) on delete cascade,
  content       text not null check (content <> ''),
  is_completed  boolean not null default false,
  realized_at   timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- entity_type is project, habit or notebook (older boards may also hold task or event links).
create table if not exists public.vision_linked_elements (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  vision_id    bigint not null references public.vision_boards (id) on delete cascade,
  entity_type  text not null,
  entity_id    bigint not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (vision_id, entity_type, entity_id)
);

create table if not exists public.vision_blocks (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  vision_id   bigint not null references public.vision_boards (id) on delete cascade,
  block_type  text not null,
  content     jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Scrapbook libraries keep their images inline as data:image URLs.
create table if not exists public.scrapbook_pads (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name        text not null default '',
  src         text not null,
  width       integer not null default 0,
  height      integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.scrapbook_stickers (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  collection  text not null default 'My stickers',
  name        text not null default '',
  src         text not null,
  width       integer not null default 0,
  height      integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.scrapbook_palettes (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name        text not null default '',
  colors      jsonb not null default '[]'::jsonb,
  source      text not null default 'custom' check (source in ('custom', 'photo')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

/* ---------- Vault ---------- */

create table if not exists public.vault_shelves (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title       text not null check (title <> ''),
  sort_order  integer not null default 0,
  tab_color   text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.vault_stacks (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title       text not null check (title <> ''),
  sort_order  integer not null default 0,
  shelf_id    bigint references public.vault_shelves (id) on delete cascade,
  slot        integer,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.vault_notebooks (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title        text not null check (title <> ''),
  stack_id     bigint references public.vault_stacks (id) on delete set null,
  cover_color  text,
  cover_image  text,
  spine_color  text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create table if not exists public.vault_chapters (
  id                bigint generated by default as identity primary key,
  user_id           uuid not null default auth.uid() references auth.users (id) on delete cascade,
  notebook_id       bigint not null references public.vault_notebooks (id) on delete cascade,
  chapter_index     integer not null,
  title             text not null check (title <> ''),
  background_color  text,
  background_image  text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- A line is a plain line, a foldout page (which can hold nested lines) or an outline section.
create table if not exists public.vault_lines (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  chapter_id  bigint not null references public.vault_chapters (id) on delete cascade,
  parent_id   bigint references public.vault_lines (id) on delete cascade,
  kind        text not null default 'line' check (kind in ('line', 'foldout', 'outline')),
  collapsed   boolean not null default false,
  sort_order  integer,
  content     text not null default '',
  blocks      jsonb not null default '[]'::jsonb,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.reference_folders (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users (id) on delete cascade,
  name        text not null check (name <> ''),
  parent_id   bigint references public.reference_folders (id) on delete set null,
  icon        text not null default '📁',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

/* ---------- Indexes ---------- */

create index if not exists vision_boards_user_idx
  on public.vision_boards (user_id, status, created_at desc);
create index if not exists vision_goals_vision_idx
  on public.vision_goals (vision_id, created_at);
create index if not exists vision_linked_elements_vision_idx
  on public.vision_linked_elements (vision_id);
create index if not exists vision_blocks_vision_idx
  on public.vision_blocks (vision_id, created_at);
create index if not exists scrapbook_stickers_collection_idx
  on public.scrapbook_stickers (user_id, collection, id);
create index if not exists vault_shelves_user_idx
  on public.vault_shelves (user_id, sort_order);
create index if not exists vault_stacks_shelf_idx
  on public.vault_stacks (shelf_id, slot);
create index if not exists vault_notebooks_stack_idx
  on public.vault_notebooks (stack_id);
create index if not exists vault_chapters_notebook_idx
  on public.vault_chapters (notebook_id, chapter_index);
create index if not exists vault_lines_chapter_idx
  on public.vault_lines (chapter_id, sort_order);
create index if not exists vault_lines_parent_idx
  on public.vault_lines (parent_id);
create index if not exists reference_folders_parent_idx
  on public.reference_folders (parent_id);
create index if not exists sparks_reference_folder_idx
  on public.sparks (user_id, folder_id) where item_type = 'reference';
-- Legacy reads graduated trackers.
create index if not exists sparks_graduated_idx
  on public.sparks (user_id, item_type, graduated_at desc) where graduated_at is not null;

/* ---------- updated_at triggers, RLS switch and grants ---------- */

do $$
declare
  t text;
begin
  foreach t in array array[
    'vision_boards', 'vision_goals', 'vision_linked_elements', 'vision_blocks',
    'scrapbook_pads', 'scrapbook_stickers', 'scrapbook_palettes',
    'vault_shelves', 'vault_stacks', 'vault_notebooks', 'vault_chapters', 'vault_lines',
    'reference_folders'
  ] loop
    execute format('drop trigger if exists %I on public.%I', t || '_touch_updated_at', t);
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.ficus_touch_updated_at()',
      t || '_touch_updated_at', t
    );
    execute format('alter table public.%I enable row level security', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
    execute format('revoke all on public.%I from anon', t);
  end loop;
end
$$;

/* ---------- Row Level Security ---------- */
-- Each signed-in user can only see and change their own rows, and can only
-- attach a row to a parent (board, shelf, stack, notebook, chapter, folder) they own.

-- Tables without a parent.
do $$
declare
  t text;
begin
  foreach t in array array[
    'vision_boards', 'scrapbook_pads', 'scrapbook_stickers', 'scrapbook_palettes', 'vault_shelves'
  ] loop
    execute format('drop policy if exists %I on public.%I', 'Users manage their own ' || t, t);
    execute format(
      'create policy %I on public.%I for all to authenticated '
      'using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)',
      'Users manage their own ' || t, t
    );
  end loop;
end
$$;

-- Goals, linked elements and blocks belong to a board.
do $$
declare
  t text;
begin
  foreach t in array array['vision_goals', 'vision_linked_elements', 'vision_blocks'] loop
    execute format('drop policy if exists %I on public.%I', 'Users manage their own ' || t, t);
    execute format(
      'create policy %I on public.%I for all to authenticated '
      'using ((select auth.uid()) = user_id) '
      'with check ((select auth.uid()) = user_id and exists ('
      '  select 1 from public.vision_boards b where b.id = vision_id and b.user_id = (select auth.uid())'
      '))',
      'Users manage their own ' || t, t
    );
  end loop;
end
$$;

drop policy if exists "Users manage their own vault_stacks" on public.vault_stacks;
create policy "Users manage their own vault_stacks"
  on public.vault_stacks
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and (
      shelf_id is null
      or exists (
        select 1 from public.vault_shelves s
        where s.id = shelf_id and s.user_id = (select auth.uid())
      )
    )
  );

drop policy if exists "Users manage their own vault_notebooks" on public.vault_notebooks;
create policy "Users manage their own vault_notebooks"
  on public.vault_notebooks
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and (
      stack_id is null
      or exists (
        select 1 from public.vault_stacks s
        where s.id = stack_id and s.user_id = (select auth.uid())
      )
    )
  );

drop policy if exists "Users manage their own vault_chapters" on public.vault_chapters;
create policy "Users manage their own vault_chapters"
  on public.vault_chapters
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.vault_notebooks n
      where n.id = notebook_id and n.user_id = (select auth.uid())
    )
  );

drop policy if exists "Users manage their own vault_lines" on public.vault_lines;
create policy "Users manage their own vault_lines"
  on public.vault_lines
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.vault_chapters c
      where c.id = chapter_id and c.user_id = (select auth.uid())
    )
    and (
      parent_id is null
      or exists (
        select 1 from public.vault_lines l
        where l.id = parent_id and l.user_id = (select auth.uid())
      )
    )
  );

drop policy if exists "Users manage their own reference_folders" on public.reference_folders;
create policy "Users manage their own reference_folders"
  on public.reference_folders
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and (
      parent_id is null
      or exists (
        select 1 from public.reference_folders f
        where f.id = parent_id and f.user_id = (select auth.uid())
      )
    )
  );
