-- FICUS module 9: Notepads (the pinned pads on Home, the Planner and the calendar).
-- Run once in the Supabase SQL Editor after 08_project_section_policies.sql. Safe to re-run.
--
-- Each pad belongs to one signed-in user. Row Level Security lets a user read,
-- add, change and delete only rows whose user_id is their own auth.uid(); no
-- one else (and no signed-out visitor) can see them.
--
-- `blocks` holds the pad's note, checklist, photo and media blocks. `content`
-- keeps plain or HTML text for simple pads and the item list for checklist pads.
-- Week and month pads store their period in `target_date` ("2026-W40", "2026-10").

create table if not exists public.notepads (
  id                 bigint generated by default as identity primary key,
  user_id            uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title              text not null default 'Notepad' check (title <> ''),
  start_date         date,
  end_date           date,
  color              text not null default 'gold'
                     check (color in ('sage', 'cloud', 'plum', 'coral', 'gold', 'taupe')),
  blocks             jsonb not null default '[]'::jsonb check (jsonb_typeof(blocks) = 'array'),
  content            text not null default '',
  pad_type           text not null default 'text' check (pad_type in ('text', 'checklist', 'contacts')),
  scope              text not null default 'day' check (scope in ('day', 'week', 'month', 'phase', 'project')),
  target_date        text,
  linked_phase_id    text,
  linked_project_id  bigint,
  is_pinned          integer not null default 1 check (is_pinned in (0, 1)),
  is_theme_of_day    integer not null default 0 check (is_theme_of_day in (0, 1)),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint notepads_dates_in_order check (end_date is null or start_date is null or end_date >= start_date)
);

create index if not exists notepads_user_dates_idx
  on public.notepads (user_id, start_date, end_date);
create index if not exists notepads_user_scope_idx
  on public.notepads (user_id, scope, target_date);

drop trigger if exists notepads_touch_updated_at on public.notepads;
create trigger notepads_touch_updated_at
  before update on public.notepads
  for each row execute function public.ficus_touch_updated_at();

-- Row Level Security: each signed-in user can only see and change their own pads.
alter table public.notepads enable row level security;
grant select, insert, update, delete on public.notepads to authenticated;
revoke all on public.notepads from anon;

drop policy if exists "Users manage their own notepads" on public.notepads;
drop policy if exists "Users read their own notepads" on public.notepads;
drop policy if exists "Users add their own notepads" on public.notepads;
drop policy if exists "Users change their own notepads" on public.notepads;
drop policy if exists "Users delete their own notepads" on public.notepads;

create policy "Users read their own notepads"
  on public.notepads
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users add their own notepads"
  on public.notepads
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users change their own notepads"
  on public.notepads
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users delete their own notepads"
  on public.notepads
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);
